import type { Entry } from '@/types';

export const ENTRIES_BY_EVENT: Record<string, Entry[]> = {
  dt1: [
    {
      id: 'dt1-1',
      eventId: 'dt1',
      startNumber: 1,
      artist: 'Greczula',
      song: 'Half of me',
      songwriters: ['Andreas Werling', 'Karl Ivert', 'Kian Sang', 'Greczula'],
    },
    {
      id: 'dt1-2',
      eventId: 'dt1',
      startNumber: 2,
      artist: 'Jacqline',
      song: 'Woman',
      songwriters: ['Dino Medanhodzic', 'Jimmy Jansson', 'Moa "Cazzi Opeia" Carlebecker', 'Thomas G:son'],
    },
    {
      id: 'dt1-3',
      eventId: 'dt1',
      startNumber: 3,
      artist: 'Noll2',
      song: 'Berusade ord',
      songwriters: ['Fredrik Andersson', 'Jakob Westerlund', 'Wilmer Öberg'],
    },
    {
      id: 'dt1-4',
      eventId: 'dt1',
      startNumber: 4,
      artist: 'Junior Lerin',
      song: 'Copacabana boy',
      songwriters: ['Fredrik Andersson'],
    },
    {
      id: 'dt1-5',
      eventId: 'dt1',
      startNumber: 5,
      artist: 'Indra',
      song: 'Beautiful lie',
      songwriters: ['Anderz Wrethov', 'Indra', 'Kristofer Strandberg', 'Laurell Barker', 'Robert Skowronski'],
    },
    {
      id: 'dt1-6',
      eventId: 'dt1',
      startNumber: 6,
      artist: 'A-Teens',
      song: 'Iconic',
      songwriters: ['Dino Medanhodzic', 'Jimmy Jansson', 'Lina Hansson', 'Moa "Cazzi Opeia" Carlebecker', 'Thomas G:son'],
    },
  ],
  dt2: [
    {
      id: 'dt2-1',
      eventId: 'dt2',
      startNumber: 1,
      artist: 'Arwin',
      song: 'Glitter',
      songwriters: ['Arwin Ismail', 'Axel Schylström', 'Dino Medanhodzic', 'Melanie Wehbe', 'Robert Skowronski'],
    },
    {
      id: 'dt2-2',
      eventId: 'dt2',
      startNumber: 2,
      artist: 'Laila Adèle',
      song: 'Oxygen',
      songwriters: ['Jonas Thander', 'Laila Adèle', 'Marcus Winther-John'],
    },
    {
      id: 'dt2-3',
      eventId: 'dt2',
      startNumber: 3,
      artist: 'Robin Bengtsson',
      song: 'Honey honey',
      songwriters: ['Gavin Jones', 'Pär Westerlund', 'Petter Tarland', 'Robin Bengtsson'],
    },
    {
      id: 'dt2-4',
      eventId: 'dt2',
      startNumber: 4,
      artist: 'Felicia',
      song: 'My system',
      songwriters: ['Audun Agnar', 'Emily Harbakk', 'Felicia', 'Julie Bergan', 'Theresa Rex'],
    },
    {
      id: 'dt2-5',
      eventId: 'dt2',
      startNumber: 5,
      artist: 'Klara Almström',
      song: 'Där hela världen väntar',
      songwriters: ['Fredrik Sonefors', 'Jimmy Jansson', 'Klara Almström'],
    },
    {
      id: 'dt2-6',
      eventId: 'dt2',
      startNumber: 6,
      artist: 'Brandsta City Släckers',
      song: 'Rakt in i elden',
      songwriters: ['Anderz Wrethov', 'Elin Wrethov', 'Kristofer Strandberg', 'Robert Skowronski'],
    },
  ],
  dt3: [
    {
      id: 'dt3-1',
      eventId: 'dt3',
      startNumber: 1,
      artist: 'Patrik Jean',
      song: 'Dusk till dawn',
      songwriters: ['David Lindgren Zacharias', 'Joy Deb', 'Melanie Wehbe', 'Patrik Jean'],
    },
    {
      id: 'dt3-2',
      eventId: 'dt3',
      startNumber: 2,
      artist: 'Korslagda',
      song: "King of Rock'n roll",
      songwriters: ['Andreas Werling', 'Pedro Sanchez', 'Kristofer Strandberg', 'Stefan "UBBE" Sjur'],
    },
    {
      id: 'dt3-3',
      eventId: 'dt3',
      startNumber: 3,
      artist: 'Emilia Pantić',
      song: 'Ingenting',
      songwriters: ['Emilia Pantić', 'Fredrik Andersson', 'Jakob Westerlund', 'Theodor Ström', 'Wilmer Öberg'],
    },
    {
      id: 'dt3-4',
      eventId: 'dt3',
      startNumber: 4,
      artist: 'Medina',
      song: "Viva l'amor",
      songwriters: ['Ali "Alibrorsh" Jammali', 'Anderz Wrethov', 'Dino Medanhodzic', 'Jimmy "Joker" Thörnfeldt', 'Sami Rekik'],
    },
    {
      id: 'dt3-5',
      eventId: 'dt3',
      startNumber: 5,
      artist: 'Eva Jumatate',
      song: 'Selfish',
      songwriters: ['Eva Jumatate', 'Herman Gardarfve', 'Marlene Strand', 'Ruth Lindegren'],
    },
    {
      id: 'dt3-6',
      eventId: 'dt3',
      startNumber: 6,
      artist: 'Saga Ludvigsson',
      song: "Ain't today",
      songwriters: ['Dino Medanhodzic', 'Jimmy Jansson', 'Johanna "Dotter" Jansson', 'Saga Ludvigsson'],
    },
  ],
  dt4: [
    {
      id: 'dt4-1',
      eventId: 'dt4',
      startNumber: 1,
      artist: 'Cimberly',
      song: 'Eternity',
      songwriters: ['Cimberly-Malaika Wanyonyi', 'David Lindgren Zacharias', 'Dino Medanhodzic', 'Melanie Wehbe'],
    },
    {
      id: 'dt4-2',
      eventId: 'dt4',
      startNumber: 2,
      artist: 'Timo Räisänen',
      song: 'Ingenting är efter oss',
      songwriters: ['Andreas "Giri" Lindbergh', 'Jimmy "Joker" Thörnfeldt', 'Joy Deb', 'Lina Räisänen', 'Linnea Deb', 'Timo Räisänen'],
    },
    {
      id: 'dt4-3',
      eventId: 'dt4',
      startNumber: 3,
      artist: 'Meira Omar',
      song: 'Dooset daram',
      songwriters: ['Anderz Wrethov', 'Jimmy "Joker" Thörnfeldt', 'Laurell Barker', 'Meira Omar'],
    },
    {
      id: 'dt4-4',
      eventId: 'dt4',
      startNumber: 4,
      artist: 'Felix Manu',
      song: 'Hatar att jag älskar dig',
      songwriters: ['Axel Schylström', 'Felix Manu', 'Fernand MP', 'Karl Flyckt'],
    },
    {
      id: 'dt4-5',
      eventId: 'dt4',
      startNumber: 5,
      artist: 'Erika Jonsson',
      song: 'Från landet',
      songwriters: ['Amir Aly', 'Erika Jonsson', 'Mikael Karlsson'],
    },
    {
      id: 'dt4-6',
      eventId: 'dt4',
      startNumber: 6,
      artist: 'Smash Into Pieces',
      song: 'Hollow',
      songwriters: ['Benjamin Jennebo', 'Chris Adam Hedman Sörbye', 'Per Bergquist', 'Philip Strand'],
    },
  ],
  dt5: [
    {
      id: 'dt5-1',
      eventId: 'dt5',
      startNumber: 1,
      artist: 'Alexa',
      song: 'Tongue tied',
      songwriters: ['Alexa', 'Moonshine (Jonatan Gusmark & Ludvig Evers)', 'Sunshine (Ellen Berg & Moa "Cazzi Opeia" Carlebecker)'],
    },
    {
      id: 'dt5-2',
      eventId: 'dt5',
      startNumber: 2,
      artist: 'Juliett',
      song: 'Långt från alla andra',
      songwriters: ['David Själin', 'Elias Kask', 'Herman Gardarfve', 'Ludvig Alamanos', 'Romeo Er-Melin', 'Valter Wigren'],
    },
    {
      id: 'dt5-3',
      eventId: 'dt5',
      startNumber: 3,
      artist: 'Bladë',
      song: 'Who you are',
      songwriters: ['Isa Tengblad', 'Josefina Carlbom'],
    },
    {
      id: 'dt5-4',
      eventId: 'dt5',
      startNumber: 4,
      artist: 'Lilla Al-Fadji',
      song: 'Delulu',
      songwriters: ['Daniel Réhn', 'Edward af Sillén', 'Lilla Al-Fadji', 'Fredrik Sonefors', 'Melanie Wehbe', 'Mikaela Samuelsson'],
    },
    {
      id: 'dt5-5',
      eventId: 'dt5',
      startNumber: 5,
      artist: 'Vilhelm Buchaus',
      song: "Hearts don't lie",
      songwriters: ['David Zandén', 'Isa Molin', 'Vilhelm Buchaus'],
    },
    {
      id: 'dt5-6',
      eventId: 'dt5',
      startNumber: 6,
      artist: 'Sanna Nielsen',
      song: 'Waste your love',
      songwriters: ['Jimmy Jansson', 'Peter Boström', 'Thomas G:son'],
    },
  ],
};

export const ALL_ENTRIES: Entry[] = Object.values(ENTRIES_BY_EVENT).flat();
