import type { MelloEvent } from '@/types';

export const MELLO_EVENTS: MelloEvent[] = [
  {
    id: 'dt1',
    type: 'semifinal',
    number: 1,
    name: 'Deltävling 1',
    date: '2026-01-31',
    time: '20:00',
    city: 'Linköping',
    arena: 'Saab Arena',
  },
  {
    id: 'dt2',
    type: 'semifinal',
    number: 2,
    name: 'Deltävling 2',
    date: '2026-02-07',
    time: '20:00',
    city: 'Göteborg',
    arena: 'Scandinavium',
  },
  {
    id: 'dt3',
    type: 'semifinal',
    number: 3,
    name: 'Deltävling 3',
    date: '2026-02-14',
    time: '20:00',
    city: 'Kristianstad',
    arena: 'Kristianstad Arena',
  },
  {
    id: 'dt4',
    type: 'semifinal',
    number: 4,
    name: 'Deltävling 4',
    date: '2026-02-21',
    time: '20:00',
    city: 'Malmö',
    arena: 'Malmö Arena',
  },
  {
    id: 'dt5',
    type: 'semifinal',
    number: 5,
    name: 'Deltävling 5',
    date: '2026-02-28',
    time: '20:00',
    city: 'Sundsvall',
    arena: 'Gärdehov Arena',
  },
  {
    id: 'finalkval',
    type: 'finalkval',
    name: 'Finalkval',
    date: '2026-02-28',
    time: '21:30',
    city: 'Sundsvall',
    arena: 'Gärdehov Arena',
  },
  {
    id: 'final',
    type: 'final',
    name: 'Final',
    date: '2026-03-07',
    time: '20:00',
    city: 'Stockholm',
    arena: 'Strawberry Arena',
  },
];
